import { CodegenConfig } from '@graphql-codegen/cli'
import 'dotenv/config'

const config: CodegenConfig = {
  overwrite: true,
  schema: [
    {
      'https://api.start.gg/gql/alpha': {
        headers: {
          // it is required that you have an .env file in the root of the renderer folder with the key-value pair VITE_STARTGG_AUTH_TOKEN="Bearer (your key here)" if you want to generate new apollo query files
          Authorization: `${process.env.VITE_STARTGG_AUTH_TOKEN}`,
          'Content-Type': 'application/json'
        }
      }
    }
  ],
  // This assumes that all your source files are in a top-level `src/` directory - you might need to adjust this to your file structure
  documents: ['src/renderer/src/lib/**/*.{ts,tsx}'],
  // Don't exit with non-zero status when there are no documents
  ignoreNoDocuments: true,
  generates: {
    './src/renderer/src/lib/types/__generated__/graphql.ts': {
      plugins: ['typescript']
    },
    './src/renderer/src/lib': {
      preset: 'near-operation-file',
      presetConfig: {
        // This should be the file generated by the "typescript" plugin above,
        // relative to the directory specified for this configuration
        baseTypesPath: './types/__generated__/graphql.ts'
      },
      plugins: ['typescript-operations', 'typed-document-node'],
      // Note: these config options moved from the other generated file config
      config: {
        avoidOptionals: {
          // Use `null` for nullable fields instead of optionals
          field: true,
          // Allow nullable input fields to remain unspecified
          inputValue: false
        },
        // Use `unknown` instead of `any` for unconfigured scalars
        defaultScalarType: 'unknown',
        // Apollo Client always includes `__typename` fields
        nonOptionalTypename: true,
        // Apollo Client doesn't add the `__typename` field to root types so
        // don't generate a type for the `__typename` for root operation types.
        skipTypeNameForRoot: true
      }
    }
  }
}

export default config
