import { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  overwrite: true,
  schema: [
    {
      "https://api.start.gg/gql/alpha": {
        headers: {
          // it is required that you have an .env file in the root of the renderer folder with the key-value pair VITE_STARTGG_AUTH_TOKEN="Bearer (your key here)" if you want to generate new apollo query files
          Authorization: `Bearer (your key here)`,
          "Content-Type": "application/json",
        },
      },
    },
  ],
  // This assumes that all your source files are in a top-level `src/` directory - you might need to adjust this to your file structure
  documents: ["src/utils/**/*.{ts,tsx}"],
  // Don't exit with non-zero status when there are no documents
  ignoreNoDocuments: true,
  generates: {
    "./src/types/__generated__/graphql.ts": {
      plugins: ["typescript-operations"],
      config: {
        // Apollo Client always includes `__typename` fields
        nonOptionalTypename: true,
        // Apollo Client doesn't add the `__typename` field to root types so
        // don't generate a type for the `__typename` for root operation types.
        skipTypeNameForRoot: true,
      }
    },
    "./src/types/__generated__/graphql-types.ts": {
      plugins: ["typescript-operations", "typed-document-node"],
      // Note: these config options moved from the other generated file config
      config: {
        // This is the file generated by the `typescript-operations` plugin above,
        // relative to the current working directory.
        importSchemaTypesFrom: "./src/types/__generated__/graphql.ts",
        // Apollo Client always includes `__typename` fields
        nonOptionalTypename: true,
        // Apollo Client doesn't add the `__typename` field to root types so
        // don't generate a type for the `__typename` for root operation types.
        skipTypeNameForRoot: true,
      },
    },
  },
};

export default config;
